### ISSUE TITLE
Poor DevEx

### ISSUE THREAD

**Issue by ltfschoen** [paseo-network/paseo-action-submission#103]
Since the issue was previously raised on 8th March 2024, there still seem to be strict entry rules for providers that aren't eligible because they don't have a certain track record due to the expectations around stability (i.e. they weren't already running production infrastructure and they are part of the 1KV). 
If they pass the string entry rules they get airdropped at least ~100k PAS, and may get nominated with ~1M PAS by a genesis account so they can compete in the active set.
Until a call is made that the to revisit the criteria once a "more mature network state" has been reached, however that is defined, those that aren't eligible despite having adequate infrastructure experience (e.g. https://github.com/paseo-network/paseo-action-submission/pull/49) as mentioned in this blogpost https://grillapp.net/12908/story-of-running-a-waiting-validator-on-paseo-testnet-89112?ref=12343 are still able to go out of pocket to run a validator node, but they won't be backed by a genesis nominator or get airdropped that ~100-200k PAS, so they can only run a full node, or alternatively the only way to accumulate the ~1M PAS tokens to contribute and compete is by spending time requesting testnet tokens from the faucet 100 PAS tokens at a time by passing the CAPTCHA PoW test each time, which could take ~20 days straight, as shown in this screen video which shows an example of someone trying to pass the CAPTCHA test to get 100 PAS tokens https://x.com/ltfschoen/status/1776097315050442809.
For small infrastructure teams, that can't find human resources willing to spend ~20 days trying to pass CAPTCHA tests to accumulate the necessary ~1M PAS, that could instead mean open-source Polkadot developers that would otherwise be working on core protocol development instead divert their time to spending ~20 days trying to pass CAPTCHA tests to accumulate the necessary ~1M PAS.
Even if they wanted to create a proposal to the Paseo treasury to request ~1M to be airdropped to them, they'd need 5% of that amount just to create the proposal 50k PAS, which could take up to ~1 day of continuously trying to pass CAPTCHA tests.  
I think the Paseo team should consider ways to relaxing the entry criteria.

**Comment by hbulgarini** [comment]
Hello Luke,

Thank you very much for your interest in Paseo and for sharing your insights. I understand that you have been contacted privately regarding your concerns; however, I believe it is beneficial to clarify our position publicly for the benefit of all our stakeholders.

Paseo is a testnet designed to offer stability for Polkadot developers as they test their projects, including parachains, wallets, and APIs. This initiative was developed in response to the instability experienced with Rococo during previous Polkadot protocol tests. One of the fundamental promises of Paseo, which was confirmed and endorsed by Polkadot stakeholders during our governance proposal vote, is its stability.

Given these requirements, the Paseo core team, along with our bounty curators, has established specific acceptance criteria for validators and system chain collators. These criteria require demonstrated experience in managing production-level infrastructure.

You can find more details about the criteria and application process in our governance document: [PAS-1-onboard_infrastructure_providers.md](https://github.com/paseo-network/paseo-action-submission/blob/main/pas/PAS-1-onboard_infrastructure_providers.md). It’s important to note that onboarding as a validator in Paseo is not a permissionless process. Validators cannot simply set up a node and accumulate PAS tokens across multiple accounts to join the validator set.

Paseo’s project complexity extends beyond technical issues—it involves coordinating a diverse network of participants including core support groups, curator organizations, infrastructure providers (currently about 20), and primarily, the Polkadot developers, who are our main user base at this time. During this initial phase, effective coordination is critical, and therefore, we must manage the number of involved parties carefully to avoid overwhelming the system. Rest assured, should opportunities for new infrastructure providers arise, you will be among the first we consider.

I want to clarify that the challenges you are experiencing are not indicative of poor developer experience but are instead a result of deliberate and agreed-upon strategies to ensure the stability and integrity of the Paseo network, as voted on by Polkadot stakeholders.

If you are keen to build more experience with production infrastructure, you might consider connecting with the administrators of the Westend testnet or joining a collective such as the IBP, which offers a comprehensive pathway for development.

Thank you again for your commitment to Paseo.

PS: Please note that we will begin to implement measures against accounts holding over 1,000 PAS to prevent excessive accumulation of balances in relay chain accounts.
