### ISSUE TITLE
Polkadot Multisig for Bounty curators.

### ISSUE THREAD

**Issue by hbulgarini** [paseo-network/paseo-action-submission#13]
TODO: List the bounty curators.

**Comment by lovelaced** [comment]
My address is `1erinozp829iWKdSTeik8TWjtnU4DCX4WntDwdiwN5mMjWH`

**Comment by al3mart** [comment]
Polkadot address: `1A13Vuern2hQMFHFxDP9vngPtfjnpnVyCiXgYpaiTYo8qFb`

**Comment by hbulgarini** [comment]
> Polkadot address: `1A13Vuern2hQMFHFxDP9vngPtfjnpnVyCiXgYpaiTYo8qFb`
> 
> _I am definitely way less patient than lovelaced :P_

Just to confirm, either Portico, R0GUE or Zondax will be bounty curators.

**Comment by wilwade** [comment]
Polkadot Address: `12WLEg326iCERNyUMU29juvuP16W9dE4nfCtNm32SMD4dTHS`
