### ISSUE TITLE
PAS for specifying the monitoring bot.

### ISSUE THREAD

**Issue by hbulgarini** [paseo-network/paseo-action-submission#23]
Bot Development:
Large Balance Monitoring: Keeping track of significant balance changes in the network.
OpenGov Monitoring: Monitoring governance activities and proposals.

@educlerici-zondax we should add Carlo to this repository as maintainer and assign this issue to him since in our last meeting he presented a very cool idea for the bot.

**Comment by hbulgarini** [comment]
To review : https://github.com/paritytech/substrate-api-sidecar

**Comment by carlosala** [comment]
If we end up integrating Subscan https://github.com/paseo-network/support/issues/6 it'd be really easy to create the bot using their API.

**Comment by educlerici-zondax** [comment]
@carlosala which approach we may use?
With Subscan or maybe with Telemetry that is already implemented?

**Comment by carlosala** [comment]
@educlerici-zondax We could use subscan for everything 👍🏻
