### ISSUE TITLE
RFC to document runtime support model

### ISSUE THREAD

**Issue by hbulgarini** [paseo-network/paseo-action-submission#5]
This issue aims to document the scope of the support and communication model for Paseo network that is going to be provided by Portico, R0GUE and Zondax organizations.

All the discussions logged here will serve as brainstorming that we land in a proper .MD file on this repository.

**Comment by hbulgarini** [comment]
also i think we should put some monitoring in place to measure the uptime of the validators.

**Comment by al3mart** [comment]
Agreed with some monitoring tooling 👍

Regarding the following:
 
>   Upgrading pallets and substrate crates.
>   Analysing if configuration for new/existing pallets should be adapted into Paseo requirements.

I think I see what you are saying, though I might express that differently. At the end of the day this chain tries to follow Polkadot as closely as possible, applying the same changes on every runtime upgrade. Granted it doesn't have any pallet that doesn't exist in Polkadot.

My understanding about the scope of work around the relay chain is that we will apply all the required pallet configuration changes to keep Paseo's and Polkadot's runtimes as close to each other as possible. Making sure that all upgrade happen in a timely manner and no downtime.
At the same time I believe is up to us to make sure that changes like, for instance, a new key type needs to be present in the nodes, or the removal of a pallet happen seamlessly for both, the maintainers of the network and its users.

**Comment by hbulgarini** [comment]
Items dicussed and to be agreed:

Communication:

Twitter account: To work as RSS + promoting news.

Support Channel Model: 

- One open Matrix channel for Developers. (TBD) Open question: should we 
- Bridge the Matrix channel to Discord.

- Open a new Github repository for support and incident management. Labeling the two categories making the triage onmce a day for labeling and actioning. 

SLA for the support service.

- Acknowledgment: TBD
- Resolution: TBD

Coretime:

To define the service once coretime arrives on Polkadot. This will need to add some process to determine how coretime is going to be assigned to parachains. (maybe we can rely on zones that me manage)

Support target:

What users are we going to support and which ones are out of the scope, i.e:

- Parachains
- Wallets
- API builders
- Validators.
- Custodians.

**Comment by hbulgarini** [comment]
> Agreed with some monitoring tooling 👍
> 
> Regarding the following:
> 
> > Upgrading pallets and substrate crates.
> > Analysing if configuration for new/existing pallets should be adapted into Paseo requirements.
> 
> I think I see what you are saying, though I might express that differently. At the end of the day this chain tries to follow Polkadot as closely as possible, applying the same changes on every runtime upgrade. Granted it doesn't have any pallet that doesn't exist in Polkadot.
> 
> My understanding about the scope of work around the relay chain is that we will apply all the required pallet configuration changes to keep Paseo's and Polkadot's runtimes as close to each other as possible. Making sure that all upgrade happen in a timely manner and no downtime. At the same time I believe is up to us to make sure that changes like, for instance, a new key type needs to be present in the nodes, or the removal of a pallet happen seamlessly for both, the maintainers of the network and its users.

Good point. My answer is: Yes and no :)

For example, we don't have the exact same values for session times, so even if staking is similar to polkadot it has different values. I wonder if fore coretime for example we should do some needed deviation as well.

**Comment by hbulgarini** [comment]
> @hbulgarini we can take care of this point if you agree
> 
> * Open a new Github repository for support and incident management. Labeling the two categories making the triage once a day for labeling and actioning.
> 
> Also i can start drafting a process for this, so the community can know How to submit and incident or support, and what to do in the middle, and what to do after solve it.

amazing! go ahead! we could include the process in the README.md maybe?

**Comment by hbulgarini** [comment]
### Runtime and network management specifics:

- Relay chain runtime maintenance:
  - Analysing if configuration for new/existing pallets should be adapted into Paseo requirements.
- Runtime Upgrade testing and coordination.
  - For each runtime upgrade, run local dry-runs with live state to guarantee availability of the network.
  - Take care of backporting changes as they happen in production networks.
- Support model:
  - Support tasks:
    - Provide means to apply solutions for bricked parachains when needed (from the relay chain perspective).
    - XCM HRMP channels management.
    - XCM debugging for parachains support cases.
    - Until we have coretime, assign slots for parachains to connect to Paseo.
    - Create and maintain Paseo Github org.
    - As hardware is going to be different from Polkadot, weights will have to be re-benchmarked.
    - Building the deterministic runtime artefact.
    - Document in form of RFCs any design decision and parameters changes.
- Big balances and OpenGov monitoring to deflect potentially harmful proposals (develop monitoring tool)
- Indexers 
- Validators monitoring.
 - System Chains:
   - Assethub.
   - Bridgehub.
   - People.
   - Coretime.
   - Collectives.

**Comment by educlerici-zondax** [comment]
@hbulgarini may i create a PR with all these improvements?
