### ISSUE TITLE
Make all initial validators to submit their application.

### ISSUE THREAD

**Issue by hbulgarini** [paseo-network/paseo-action-submission#72]
- [x] Build a list of Paseo validators which were part of the launch but that are not registered through the process.
- [x] Ask one by one to submit their application.

**Comment by educlerici-zondax** [comment]
- [List of Paseo validators which were part of the launch but that are not registered through the process.](https://docs.google.com/document/d/1_6YDbOytTHHye_VCpjbkeSked6Oi0bOEMyZ-VmRCCQM/edit?usp=sharing)

**Comment by hbulgarini** [comment]
@educlerici-zondax i think we have addressed them all right?

**Comment by educlerici-zondax** [comment]
i will do a new update today and will be back with definitions

**Comment by educlerici-zondax** [comment]
@hbulgarini do you agree to close this task?
